### ISSUE TITLE
Weird js rebuild issue

### ISSUE THREAD

**Issue by kumavis** [airship-industries/about-vapor#2]
`Uncaught TypeError: Cannot read property '0' of undefined`

getting a strange problem on rebuild from watchify
Here is the build code. [sorry about all the gulp](https://github.com/ethereum/vapor/blob/master/gulpfile.js).

I have two entry points and two build modes, for a total of four browserify builds. For all four, I'm using this gulp task generator I threw together [at the bottom](https://github.com/ethereum/vapor/blob/master/gulpfile.js#L146-L185).
only the sandbox.js bundle is giving me a problem, and only on subsequent builds (not the first one)

![image](https://cloud.githubusercontent.com/assets/1474978/6406877/d78bbff8-bdea-11e4-8a29-4f40283a5382.png)

**Comment by kumavis** [comment]
```
 Uncaught TypeError: Cannot read property '0' of undefinedsandbox.js:formatted:26317 /Users/kumavis/Development/Node/vapor/node_modules/xtend/immutable.jssandbox.js:formatted:14 ssandbox.js:formatted:16 (anonymous function)sandbox.js:formatted:28 (anonymous function)sandbox.js:formatted:157 ./app/sandbox.js.buffersandbox.js:formatted:14 ssandbox.js:formatted:23 esandbox.js:formatted:25 (anonymous function)
```

**Comment by kumavis** [comment]
plantext stack
```
Uncaught TypeError: Cannot read property '0' of undefined
sandbox.js:formatted:26317
   
/Users/kumavis/Development/Node/vapor/node_modules/xtend/immutable.js
sandbox.js:formatted:26317
  
s
sandbox.js:formatted:14
   
(anonymous function)
ssandbox.js:formatted:16 
  
(anonymous function)
sandbox.js:formatted:28

./app/sandbox.js.buffer
sandbox.js:formatted:157

s
sandbox.js:formatted:14

e
sandbox.js:formatted:23 

(anonymous function)
sandbox.js:formatted:25
```

**Comment by kumavis** [comment]
related? https://github.com/substack/watchify/issues/130

**Comment by zertosh** [comment]
Looking at your gulpfile, I think that your watchify instances are all sharing the same cache but shouldn't be. Try:

```js
// from this:
bundler = bundler || watchify(browserify(entryPoint, watchify.args))
// to that:
bundler = bundler || watchify(browserify(entryPoint, {cache: {}, packageCache: {}}))
```

**Comment by zertosh** [comment]
Sorry meant to post this in https://github.com/substack/watchify/issues/148
